// This list has a lot of profanity, slurs, and other offensive words.
// I mean it, do not look at it unless you are 18+ and contributing to the project.
// Back down now....
// I am telling you....

// I really mean it. Do not do it.

// Come on, you can do better.
// I am telling you....
// I really mean it. Do not do it.
// I am telling you....

// come on, it's time to leave, do not scroll down

// you are closer, don't do it.

// There you go that's it.

export const UNALLOWED_WORDS = {
  profanity: [
    'cunt',
    'twat',
    'prick',
    'whore',
    'slut',
    'cocksucker',
    'dipshit',
    'shithead',
    'shitface',
    'asswipe',
    'dickhead',
    'cockface',
    'bitch',
    'douche',
    'jackass',
    'jerk',
    'idiot',
  ],
  slurs: [
    'nigger',
    'nigga',
    'chink',
    'gook',
    'spic',
    'wetback',
    'kike',
    'faggot',
    'fag',
    'dyke',
    'tranny',
    'retard',
    'cripple',
    'coon',
    'towelhead',
    'sandnigger',
    'beaner',
    'gyppo',
    'jap',
    'paki',
    'porchmonkey',
    'raghead',
    'cameljockey',
    'heeb',
    'yid',
    'mongoloid',
    'savage',
    'halfbreed',
    'house nigger',
    'queer',
    'cholo',
    'redneck',
    'whitey',
    'trannies',
    'spook',
    'slants',
    'wop',
  ],
  nsfw: [
    'semen',
    'blowjob',
    'deepthroat',
    'anal',
    'dildo',
    'pussylick',
    'handjob',
    'assfuck',
    'rimjob',
    'cuntlick',
    'titfuck',
    'bukkake',
    'gangbang',
    'orgy',
    'fuckfest',
    'cumshot',
    'facials',
    'creampie',
    'pussyjuice',
    'pegging',
    'scissoring',
    'felching',
    'squirting',
    'fisting',
    'rimming',
    'buttplug',
    'bondage',
    'bdsm',
    'cockring',
    'doggystyle',
    'gloryhole',
    'gaping',
    'snowballing',
    'footjob',
    'cuckold',
    'pegged',
    'choking',
    'slutty',
    'pervert',
    'creep',
  ],
  sexualViolence: [
    'rape',
    'rapist',
    'raping',
    'molest',
    'molester',
    'molestation',
    'sexualassault',
    'sexualharassment',
    'incest',
    'pedo',
    'pedophile',
    'pedophilia',
    'childporn',
    'cp',
    'bestiality',
    'zoophilia',
    'necrophilia',
    'snuff',
    'forcedsex',
    'nonconsensual',
    'abduction',
    'grooming',
    'traffick',
    'humantrafficking',
    'childabuse',
    'statutoryrape',
    'stalker',
    'stalking',
  ],
};
